name: PR Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1 #V1은  Azul Zulu OpenJDK만 지원
        with:
          java-version: 17

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # Gradle test를 실행한다
      - name: Test with Maven
        run: ./mvnw test